apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: otrs
data:
  otrs-realm.json: |
    {
      "realm": "otrs",
      "enabled": true,
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "clients": [
        {
          "clientId": "otrs-ce",
          "name": "OTRS Community Edition",
          "enabled": true,
          "publicClient": false,
          "secret": "otrs-keycloak-secret",
          "redirectUris": [
            "http://192.168.139.2/otrs-auth/login"
          ],
          "webOrigins": [
            "http://192.168.139.2",
            "+"
          ],
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "protocol": "openid-connect",
          "attributes": {
            "post.logout.redirect.uris": "http://192.168.139.2/otrs/index.pl"
          },
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "profile",
            "roles",
            "email"
          ]
        }
      ],
      "users": [
        {
          "username": "root@localhost",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Admin",
          "lastName": "OTRS",
          "email": "root@localhost",
          "credentials": [
            {
              "type": "password",
              "value": "Admin@123",
              "temporary": false
            }
          ]
        }
      ]
    }
