apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otrs

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-pvc.yaml
  - mysql-init-configmap.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - otrs-pvc.yaml
  - otrs-configmap.yaml
  - otrs-deployment.yaml
  - otrs-service.yaml
