apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: otrs
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: otrs-root-secret
  MYSQL_DATABASE: otrs
  MYSQL_USER: otrs
  MYSQL_PASSWORD: otrs-db-secret
