apiVersion: v1
kind: ConfigMap
metadata:
  name: otrs-oidc-config
  namespace: otrs
data:
  # Update OTRS_FQDN and OTRS_KEYCLOAK_ISSUER after `kubectl -n otrs get svc`
  # to match the LoadBalancer external IPs of otrs and keycloak services.
  OTRS_KEYCLOAK_ENABLED: "1"
  OTRS_FQDN: "192.168.139.2"
  OTRS_HTTP_TYPE: "http"
  OTRS_SCRIPT_ALIAS: "otrs/"
  OTRS_KEYCLOAK_ISSUER: "http://192.168.139.2:8080/realms/otrs"
  OTRS_KEYCLOAK_INTERNAL_ISSUER: "http://keycloak:8080/realms/otrs"
  OTRS_KEYCLOAK_CLIENT_ID: "otrs-ce"
  OTRS_KEYCLOAK_CLIENT_SECRET: "otrs-keycloak-secret"
  OTRS_KEYCLOAK_USER_ATTRIBUTE: "preferred_username"
  KC_HOSTNAME: "192.168.139.2"
  KC_HOSTNAME_PORT: "8080"
