#!/bin/bash
set -euo pipefail

write_apache_oidc_env() {
    local env_file="/etc/httpd/conf.d/zzz_otrs_oidc_env.conf"
    local vars=(
        OTRS_KEYCLOAK_ENABLED
        OTRS_FQDN
        OTRS_HTTP_TYPE
        OTRS_SCRIPT_ALIAS
        OTRS_KEYCLOAK_ISSUER
        OTRS_KEYCLOAK_INTERNAL_ISSUER
        OTRS_KEYCLOAK_HOST
        OTRS_KEYCLOAK_REALM
        OTRS_KEYCLOAK_CLIENT_ID
        OTRS_KEYCLOAK_CLIENT_SECRET
        OTRS_KEYCLOAK_USER_ATTRIBUTE
        OTRS_KEYCLOAK_USER_REGEXP
    )

    {
        echo "# Auto-generated by OTRS entrypoint."
        echo "# Apache CGI does not inherit the container environment unless SetEnv is used."
        for var in "${vars[@]}"; do
            if [[ -n "${!var:-}" ]]; then
                printf 'SetEnv %s "%s"\n' "${var}" "${!var//\"/\\\"}"
            fi
        done
    } > "${env_file}"
}

write_apache_oidc_env

# Start OTRS background services when the application is already configured.
if [[ -f /opt/otrs/Kernel/Config.pm ]] && grep -q "Database" /opt/otrs/Kernel/Config.pm; then
    /opt/otrs/bin/otrs.Daemon.pl start || true
    /opt/otrs/bin/Cron.sh start || true
fi

exec /usr/sbin/httpd -DFOREGROUND
