#!/bin/bash
set -euo pipefail

write_apache_oidc_env() {
    local env_file="/etc/httpd/conf.d/zzz_otrs_oidc_env.conf"
    local vars=(
        OTRS_KEYCLOAK_ENABLED
        OTRS_FQDN
        OTRS_HTTP_TYPE
        OTRS_SCRIPT_ALIAS
        OTRS_KEYCLOAK_ISSUER
        OTRS_KEYCLOAK_INTERNAL_ISSUER
        OTRS_KEYCLOAK_HOST
        OTRS_KEYCLOAK_REALM
        OTRS_KEYCLOAK_CLIENT_ID
        OTRS_KEYCLOAK_CLIENT_SECRET
        OTRS_KEYCLOAK_USER_ATTRIBUTE
        OTRS_KEYCLOAK_USER_REGEXP
    )

    {
        echo "# Auto-generated by OTRS entrypoint."
        echo "# Apache CGI does not inherit the container environment unless SetEnv is used."
        for var in "${vars[@]}"; do
            if [[ -n "${!var:-}" ]]; then
                printf 'SetEnv %s "%s"\n' "${var}" "${!var//\"/\\\"}"
            fi
        done
    } > "${env_file}"
}

write_apache_oidc_env

# SysConfig deploy writes ZZZAAuto.pm under /opt/otrs/Kernel during bootstrap, but
# Kubernetes mounts the kernel volume over that path. Re-sync from the database when
# the deployed cache file is missing.
if [[ -f /opt/otrs/Kernel/Config.pm ]] && [[ ! -f /opt/otrs/Kernel/Config/Files/ZZZAAuto.pm ]]; then
    echo "Missing ZZZAAuto.pm on kernel volume; syncing SysConfig from database..."
    su -s /bin/bash -c 'perl -I/opt/otrs -I/opt/otrs/Kernel/cpan-lib -I/opt/otrs/Custom -MKernel::System::ObjectManager -e '"'"'
        local \$Kernel::OM = Kernel::System::ObjectManager->new();
        my \$Success = \$Kernel::OM->Get(q{Kernel::System::SysConfig})->ConfigurationDeploySync();
        exit \$Success ? 0 : 1;
    '"'"'' otrs || echo "Warning: SysConfig sync failed."
fi

# Start OTRS background services when the application is already configured.
if [[ -f /opt/otrs/Kernel/Config.pm ]] && grep -q "Database" /opt/otrs/Kernel/Config.pm; then
    /opt/otrs/bin/otrs.Daemon.pl start || true
    /opt/otrs/bin/Cron.sh start || true
fi

exec /usr/sbin/httpd -DFOREGROUND
